### PR TITLE
Revised translation.

### PR DESCRIPTION
**Pull request by LightWayUp**
- OpenGApps now provides packages for Android 8.1 :D. 
- Revise some translations.

### CODE REVIEW

**Comment by hjthjthjt** [comment]
（论如何正确的把你的东西合并到我本地完成了一部分但是还没有推上去的代码）

**Comment by LightWayUp** [comment]
You can push your uncommitted changes after you've completed them. After that, the pull request would then be marked as having conflicts. GitHub provides a convenient tool for resolving conflicts online. Code with conflicts would be highlighted in orange by diff. You just review the code, remove the part you don't want to keep, and after all conflicts are solved, the pull request can be merged.
More details can be found in this GitHub article (with images for clearer explanation) : https://help.github.com/articles/resolving-a-merge-conflict-on-github/

:)

**Comment by hjthjthjt** [comment]
:) ok

**Comment by LightWayUp** [comment]
I've resolved all conflicts. Can you merge this pull request :)?

**Pull request merged**
